### PR TITLE
Patch 9.1.0 Spell Fixes to Old Spells

### PR DESCRIPTION
**Pull request by MMOSimca**
Reordered vs-spells.lua and corrected SpellID 107 and 200 entries.

The SpellID 200 change is very straightforward, but the SpellID 107 entry is very complicated. I'm marking it as unverified for now, but it should still be merged because it's a spell used by a popular companion.

### CODE REVIEW

**Comment by MMOSimca** [comment]
Just saw the info from #43. Incorporating that.

**Comment by Gaboros** [comment]
> Just saw the info from #43. Incorporating that.

Can't confirm 107 because there is no logs.  About 122: 
https://github.com/Gaboros/VenturePlan/issues/43#issuecomment-877841345

Are you on discord Simca? :)

**Comment by Gaboros** [comment]
> > Just saw the info from #43. Incorporating that.
> 
> Can't confirm 107 because there is no logs. About 122:
> [#43 (comment)](https://github.com/Gaboros/VenturePlan/issues/43#issuecomment-877841345)
> 
> Are you on discord Simca? :)

TBH both should be fine for 107 I think

**Comment by MMOSimca** [comment]
There's some ambiguity for 107 still based purely on data and tooltip. Tooltip implies a direct nuke that leaves a debuff. Underlying data is changed from 9.0.5 but the part that hasn't changed is that the Effect Type is still Damage Over Time % - not Damage %. This implies a DoT effect still, even though it shouldn't have that.

Need logs to clarify.

**Comment by MMOSimca** [comment]
Yeah, my Discord is Simca#7251.

**Comment by Gaboros** [comment]
[log for 107.txt](https://github.com/Gaboros/VenturePlan/files/6797447/log.for.107.txt)
I was wrongs. There are logs for 107 but because it's not an enemy spell I didn't find it on the database. (Follower spells not saved currently :( )

**Comment by MMOSimca** [comment]
Looks like the 'nuke' approach is correct for 107 based on that log. The debuff remains in following turns but isn't doing any damage.

**Comment by MMOSimca** [comment]
Those 3 spell changes (107, 122, 200) should be good to go now.

**Pull request merged**
